### PR TITLE
Russian localisation

### PR DESCRIPTION
**Pull request by Kostenkov-2021**
Russian nvda.po file has been added.

### CODE REVIEW

**Comment by CyrilleB79** [comment]
Hi @Kostenkov-2021

Thanks for your willing to localize add-ons in Russian.
For all my add-ons, I use the centralized translation framework, as explained in https://github.com/CyrilleB79/charInfo/pull/11. I do not merge directly translation pull requests.

Could you please submit your work on Character Information as well as for NVDA Dev & Test Toolbox via SVN Assembla repository (centralized translation framework)?
The first step is to subscribe to translators mailing list, if not already. On this list, you can ask for help if needed.

If you face any difficulty, please let me know.

**Comment by Kostenkov-2021** [comment]
Hello, @CyrilleB79

I have not seen any reaction on my requesting at translator's mailing list to give me access to translation framework. If you have this ability, please provide to me access to this framework. Thank you in advance.

**Comment by CyrilleB79** [comment]
I have not seen your message on the [translators mailing list](https://groups.io/g/nvda-translations/topics).
Could you double check and point me to it, or re-send it if needed?

It's important that your message appears on the list so that you can get in touch with other Russian translators. This allows you to make you known from other translators if needed and may avoid Russian translators working on the same work package.

**Comment by CyrilleB79** [comment]
I cannot see your messages [here](https://groups.io/g/nvda-translations/topics), so they are not received on the list.

Have you received any delivery error message in return? Have you also checked your spam?

Have you subscribed to the list before sending your message? And do you receive the messages from the translators list?

Are you used to groups.io mailing lists?

Don't worry, we will find the issue and solve it.

**Comment by lukaszgo1** [comment]
i had a similar problem when joining the list back in 2021. The translations group is set so that posts from new members have to be approved by the moderation, but it looks like NV Access does not monitor them regularly. To have my initial post approved I had to contact the group owner several times using their  email address given in the main page of the  group.

**Pull request closed without merging**
